import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'tables.dart';

part 'app_database.g.dart'; // generated by build_runner

@DriftDatabase(tables: [
  Profile,
  FocusSessions,
  AppUsage,
  RestrictionGroups,
  RestrictionGroupApps,
  BlockedApps,
  BedtimeSchedule,
  ScoreLog,
  EmergencyUnlocks,
  PickupsLog,
])
class AppDatabase extends _$AppDatabase {
  /// Default constructor — creates its own LazyDatabase connection.
  /// Used by providers and most of the app.
  AppDatabase() : super(_openConnection());

  /// Constructor accepting an external LazyDatabase.
  /// Used by DriftDbService for centralized DB configuration.
  AppDatabase.withExecutor(QueryExecutor executor) : super(executor);

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async => m.createAll(),
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            // v1→v2: add biometric_lock_enabled column to profile.
            // Default false (no lock) so existing users aren't locked out.
            await m.addColumn(profile, profile.biometricLockEnabled);
          }
        },
      );
}

LazyDatabase _openConnection() {
  // LazyDatabase defers opening the file until first query, off the
  // app's cold-start critical path — avoids a startup jank spike on
  // low-end devices where disk I/O + SQLite init can take 30-80ms.
  return LazyDatabase(() async {
    final dir = await getApplicationDocumentsDirectory();
    final file = File(p.join(dir.path, 'ulimit.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
